leftnav:
- identifier: 16dbf758-161f-13eb-9c02-6ce20a28c637
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 8f89a572-9fa0-aedb-bf8a-3ab2f69f609d
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 6e7c6bbe-8587-c3f4-6451-481bc871621e
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 96340cb3-df30-faca-8e02-b90f42a224c0
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: 3cdb3f14-a1c0-7553-8b3c-0d4f06606873
  name: Video
  pageRef: /pages/video
  weight: 50
